# Generated by Django 3.2.6 on 2022-04-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='golongan',
            table='_golongan',
        ),
    ]
